# fly.toml app configuration file generated for codenote on 2023-06-07T21:11:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "codenote"
primary_region = "cdg"

[http_service]
  internal_port = 5050
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
